---
test:
  name: ioheavy_write_scan_100
  description: This is ioheavy benchmark to test write and scan 100 transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: write
    txNumber:
    - 1
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    - type: fixed-rate
      opts:
        tps: 1
    arguments:
      start_key: 0
      total_key_num: 100
    callback: benchmark/ioheavy/write.js
  - label: scan
    txNumber:
    - 1
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    - type: fixed-rate
      opts:
        tps: 1
    arguments:
      start_key: 0
      total_key_num: 100
    callback: benchmark/ioheavy/scan.js
monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
