dbstore_membersrvc0:
  image: hyperledger/fabric-membersrvc
  volumes:
    - /var/hyperledger/production/db

membersrvc0:
  extends:
    file: compose-defaults.yml
    service: membersrvc
  volumes_from:
    - dbstore_membersrvc0

dbstore_vp0:
  image: hyperledger/fabric-peer
  volumes:
    - /var/hyperledger/production/db

vp0:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBase
  volumes_from:
    - dbstore_vp0
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc0
  ports:
    - 7050:6060

dbstore_vp1:
  image: hyperledger/fabric-peer
  volumes:
    - /var/hyperledger/production/db

vp1:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBase
  volumes_from:
    - dbstore_vp1
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
  links:
    - membersrvc0
    - vp0

dbstore_vp2:
  image: hyperledger/fabric-peer
  volumes:
    - /var/hyperledger/production/db

vp2:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBase
  volumes_from:
    - dbstore_vp2
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
  links:
    - membersrvc0
    - vp0

dbstore_vp3:
  image: hyperledger/fabric-peer
  volumes:
    - /var/hyperledger/production/db

vp3:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBase
  volumes_from:
    - dbstore_vp3
  environment:
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
  links:
    - membersrvc0
    - vp0
